### ISSUE TITLE
[Ubuntu 20.04] I got a parsing error "OpenSSL is not linked"

### ISSUE THREAD

**Issue by naoki85** [winebarrel/postfix_status_line#7]
Hi, I use fluent-plugin-filter-parse-postfix.
And I got the following error while parsing postfix logs.

```
[warn]: #0 failed to parse a postfix log: xxxxxx error_class=ArgumentError error="OpenSSL is not linked"
[warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/postfix_status_line-0.2.8/lib/postfix_status_line.rb:13:in `parse'
[warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/postfix_status_line-0.2.8/lib/postfix_status_line.rb:13:in `parse'
[warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-filter-parse-postfix-0.2.7/lib/fluent/plugin/filter_parse_postfix.rb:26:in `filter'
```

I tried in the following environment.
- Ubuntu 20.04
- postfix 3.4.10
- OpenSSL 1.1.1f
- Ruby 2.7.0

Is there a possible reason?

**Comment by naoki85** [comment]
Sorry, I uninstalled fluent-plugin-filter-parse-postfix and installed again, and in this time I didn't got such errors.

So I would close this issue.
